export enum UserType {
  INDIVIDUAL = 'INDIVIDUAL',
  COMMERCIAL = 'COMMERCIAL',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  INSURANCE_ADMIN = 'INSURANCE_ADMIN',
  COMMERCIAL_ADMIN = 'COMMERCIAL_ADMIN',
}

export enum ListingStatus {
  DRAFT = 'DRAFT',
  PENDING_LEGAL_CHECK = 'PENDING_LEGAL_CHECK',
  PENDING_REVIEW = 'PENDING_REVIEW',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  DELETED = 'DELETED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum SellerType {
  OWNER = 'OWNER',
  DEALER = 'DEALER',
}

export enum DamageStatus {
  NONE = 'NONE',
  PAINTED = 'PAINTED',
  REPLACED = 'REPLACED',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export enum MediaAssetPurpose {
  POST_MEDIA = 'POST_MEDIA',
  STORY_MEDIA = 'STORY_MEDIA',
  LISTING_MEDIA = 'LISTING_MEDIA',
  PROFILE_AVATAR = 'PROFILE_AVATAR',
  MESSAGE_ATTACHMENT = 'MESSAGE_ATTACHMENT',
  COMMERCIAL_DOCUMENT = 'COMMERCIAL_DOCUMENT',
  INSURANCE_OFFER = 'INSURANCE_OFFER',
  INSURANCE_POLICY = 'INSURANCE_POLICY',
  INSURANCE_INVOICE = 'INSURANCE_INVOICE',
  GARAGE_VEHICLE_MEDIA = 'GARAGE_VEHICLE_MEDIA',
}

export enum MediaVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}

export enum AttachmentType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  FILE = 'FILE',
}

export enum MessageThreadType {
  DIRECT = 'DIRECT',
  GROUP = 'GROUP',
  LISTING_DEAL = 'LISTING_DEAL',
}

export enum MessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  FILE = 'FILE',
  SYSTEM_CARD = 'SYSTEM_CARD',
}

export enum SystemMessageCardType {
  LICENSE_INFO_CARD = 'LICENSE_INFO_CARD',
  INSURANCE_OFFER_CARD = 'INSURANCE_OFFER_CARD',
  PAYMENT_STATUS_CARD = 'PAYMENT_STATUS_CARD',
  POLICY_DOCUMENT_CARD = 'POLICY_DOCUMENT_CARD',
}

export enum NotificationType {
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  COMMENT_REPLY = 'COMMENT_REPLY',
  COMMENT_LIKE = 'COMMENT_LIKE',
  FOLLOW = 'FOLLOW',
  MESSAGE = 'MESSAGE',
  LISTING_SAVED = 'LISTING_SAVED',
  INSURANCE_REQUEST_CREATED = 'INSURANCE_REQUEST_CREATED',
  INSURANCE_OFFER_READY = 'INSURANCE_OFFER_READY',
  INSURANCE_OFFER_REJECTED = 'INSURANCE_OFFER_REJECTED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  POLICY_DOCUMENT_READY = 'POLICY_DOCUMENT_READY',
  COMMERCIAL_APPLICATION_SUBMITTED = 'COMMERCIAL_APPLICATION_SUBMITTED',
  COMMERCIAL_APPLICATION_APPROVED = 'COMMERCIAL_APPLICATION_APPROVED',
  COMMERCIAL_APPLICATION_REJECTED = 'COMMERCIAL_APPLICATION_REJECTED',
  LISTING_SUSPENDED = 'LISTING_SUSPENDED',
  USER_DISABLED = 'USER_DISABLED',
}

export enum AiMessageRole {
  USER = 'USER',
  ASSISTANT = 'ASSISTANT',
  SYSTEM = 'SYSTEM',
}

export enum AiProvider {
  OPENAI = 'OPENAI',
  DEEPSEEK = 'DEEPSEEK',
  INTERNAL = 'INTERNAL',
}

export enum AiCardType {
  LISTING_CARD = 'LISTING_CARD',
  USER_CARD = 'USER_CARD',
  POST_CARD = 'POST_CARD',
  COMPARISON_CARD = 'COMPARISON_CARD',
}

export enum ListingDescriptionTone {
  PROFESSIONAL = 'PROFESSIONAL',
  FRIENDLY = 'FRIENDLY',
  SHORT = 'SHORT',
  DETAILED = 'DETAILED',
}

export enum VehicleType {
  SEDAN = 'SEDAN',
  SUV = 'SUV',
  HATCHBACK = 'HATCHBACK',
  COUPE = 'COUPE',
  PICKUP = 'PICKUP',
  VAN = 'VAN',
  MOTORCYCLE = 'MOTORCYCLE',
  OTHER = 'OTHER',
}

export enum FuelType {
  GASOLINE = 'GASOLINE',
  DIESEL = 'DIESEL',
  HYBRID = 'HYBRID',
  ELECTRIC = 'ELECTRIC',
  LPG = 'LPG',
  OTHER = 'OTHER',
}

export enum TransmissionType {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
  SEMI_AUTOMATIC = 'SEMI_AUTOMATIC',
  CVT = 'CVT',
}

export enum ObdAdapterType {
  MOCK = 'MOCK',
  BLUETOOTH = 'BLUETOOTH',
  WIFI = 'WIFI',
}

export enum ObdConnectionStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
  REVOKED = 'REVOKED',
}

export enum ObdReportStatus {
  CREATED = 'CREATED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ObdFaultSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum InsuranceRequestStatus {
  PENDING = 'PENDING',
  OFFER_CREATED = 'OFFER_CREATED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PAID = 'PAID',
  POLICY_UPLOADED = 'POLICY_UPLOADED',
  CANCELLED = 'CANCELLED',
}

export enum CommercialApplicationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum VerificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}
