export const TURKIYE_CITIES = [
  'Adana',
  'Adiyaman',
  'Afyonkarahisar',
  'Agri',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Ardahan',
  'Artvin',
  'Aydin',
  'Balikesir',
  'Bartin',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingol',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Canakkale',
  'Cankiri',
  'Corum',
  'Denizli',
  'Diyarbakir',
  'Duzce',
  'Edirne',
  'Elazig',
  'Erzincan',
  'Erzurum',
  'Eskisehir',
  'Gaziantep',
  'Giresun',
  'Gumushane',
  'Hakkari',
  'Hatay',
  'Igdir',
  'Isparta',
  'Istanbul',
  'Izmir',
  'Kahramanmaras',
  'Karabuk',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kirikkale',
  'Kirklareli',
  'Kirsehir',
  'Kilis',
  'Kocaeli',
  'Konya',
  'Kutahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Mugla',
  'Mus',
  'Nevsehir',
  'Nigde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Sanliurfa',
  'Siirt',
  'Sinop',
  'Sirnak',
  'Sivas',
  'Tekirdag',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Usak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
] as const;

export const TURKIYE_DISTRICT_SUGGESTIONS: Record<string, string[]> = {
  Ankara: ['Cankaya', 'Kecioren', 'Mamak', 'Sincan', 'Yenimahalle'],
  Bursa: ['Nilufer', 'Osmangazi', 'Yildirim', 'Gursu', 'Inegol'],
  Istanbul: ['Besiktas', 'Kadikoy', 'Sisli', 'Umraniye', 'Uskudar'],
  Izmir: ['Bornova', 'Buca', 'Karsiyaka', 'Konak', 'Menemen'],
  Kocaeli: ['Gebze', 'Golcuk', 'Izmit', 'Kartepe', 'Korfez'],
};
