const TYPE = {
  CAR: 'AUTOMOBILE',
  MOTORCYCLE: 'MOTORCYCLE',
  COMMERCIAL: 'COMMERCIAL',
};

const SOURCE = {
  MANUAL_SEED: 'MANUAL_SEED',
  CARLOI_SEED: 'CARLOI_SEED',
};

function slugify(value) {
  return value
    .toLocaleLowerCase('en-US')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');
}

function model(name, options = {}) {
  return {
    name,
    slug: options.slug ?? slugify(name),
    catalogType: options.catalogType ?? TYPE.CAR,
    yearStart: options.yearStart ?? null,
    yearEnd: options.yearEnd ?? null,
    bodyType: options.bodyType ?? null,
    isActive: options.isActive ?? true,
    source: options.source ?? SOURCE.MANUAL_SEED,
    manualReviewNeeded: options.manualReviewNeeded ?? false,
  };
}

function reviewModel(name, options = {}) {
  return model(name, {
    ...options,
    manualReviewNeeded: true,
    source: SOURCE.MANUAL_SEED,
  });
}

function brand({ name, slug, type = TYPE.CAR, country = null, models = [] }) {
  return {
    brand: {
      name,
      slug: slug ?? slugify(name),
      type,
      country,
      isActive: true,
    },
    models,
  };
}

const PHASE1_VEHICLE_MODEL_BRANDS = [
  brand({ name: 'Abarth', country: 'Italy', models: [
    model('500', { yearStart: 2008, bodyType: 'Hatchback' }),
    model('595', { yearStart: 2012, bodyType: 'Hatchback' }),
    model('695', { yearStart: 2012, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Aion', country: 'China', models: [
    model('Y', { yearStart: 2021, bodyType: 'SUV' }),
    model('S', { yearStart: 2019, bodyType: 'Sedan' }),
    model('V', { yearStart: 2020, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Alfa Romeo', country: 'Italy', models: [
    model('MiTo', { yearStart: 2008, yearEnd: 2018, bodyType: 'Hatchback' }),
    model('Giulietta', { yearStart: 2010, yearEnd: 2020, bodyType: 'Hatchback' }),
    model('Giulia', { yearStart: 2016, bodyType: 'Sedan' }),
    model('Stelvio', { yearStart: 2017, bodyType: 'SUV' }),
    model('Tonale', { yearStart: 2022, bodyType: 'SUV' }),
    model('159', { yearStart: 2005, yearEnd: 2011, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Alpine', country: 'France', models: [
    model('A110', { yearStart: 2017, bodyType: 'Coupe' }),
    model('A310', { yearStart: 1971, yearEnd: 1984, bodyType: 'Coupe' }),
    model('A290', { yearStart: 2024, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Anadol', country: 'Turkey', models: [
    model('A1', { yearStart: 1966, yearEnd: 1975, bodyType: 'Coupe' }),
    model('A2', { yearStart: 1970, yearEnd: 1981, bodyType: 'Sedan' }),
    model('STC-16', { yearStart: 1973, yearEnd: 1975, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Arora', country: 'Turkey', type: TYPE.MOTORCYCLE, models: [
    model('AR 50', { catalogType: TYPE.MOTORCYCLE, yearStart: 2010, bodyType: 'Motosiklet' }),
    model('Freedom', { catalogType: TYPE.MOTORCYCLE, yearStart: 2015, bodyType: 'Motosiklet' }),
    model('Cappucino', { catalogType: TYPE.MOTORCYCLE, yearStart: 2020, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Aston Martin', country: 'United Kingdom', models: [
    model('Vantage', { yearStart: 2005, bodyType: 'Coupe' }),
    model('DB11', { yearStart: 2016, bodyType: 'Coupe' }),
    model('DBX', { yearStart: 2020, bodyType: 'SUV' }),
    model('DBS', { yearStart: 2007, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Audi', country: 'Germany', models: [
    model('A1', { yearStart: 2010, bodyType: 'Hatchback' }),
    model('A3', { yearStart: 1996, bodyType: 'Hatchback' }),
    model('A4', { yearStart: 1994, bodyType: 'Sedan' }),
    model('A5', { yearStart: 2007, bodyType: 'Coupe' }),
    model('A6', { yearStart: 1994, bodyType: 'Sedan' }),
    model('Q2', { yearStart: 2016, bodyType: 'SUV' }),
    model('Q3', { yearStart: 2011, bodyType: 'SUV' }),
    model('Q5', { yearStart: 2008, bodyType: 'SUV' }),
    model('Q7', { yearStart: 2005, bodyType: 'SUV' }),
    model('TT', { yearStart: 1998, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Bentley', country: 'United Kingdom', models: [
    model('Continental GT', { yearStart: 2003, bodyType: 'Coupe' }),
    model('Flying Spur', { yearStart: 2005, bodyType: 'Sedan' }),
    model('Bentayga', { yearStart: 2015, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'BMW', country: 'Germany', models: [
    model('1 Series', { slug: '1-series', yearStart: 2004, bodyType: 'Hatchback' }),
    model('3 Series', { slug: '3-series', yearStart: 1975, bodyType: 'Sedan' }),
    model('4 Series', { slug: '4-series', yearStart: 2013, bodyType: 'Coupe' }),
    model('5 Series', { slug: '5-series', yearStart: 1972, bodyType: 'Sedan' }),
    model('7 Series', { slug: '7-series', yearStart: 1977, bodyType: 'Sedan' }),
    model('X1', { yearStart: 2009, bodyType: 'SUV' }),
    model('X3', { yearStart: 2003, bodyType: 'SUV' }),
    model('X5', { yearStart: 1999, bodyType: 'SUV' }),
    model('R 1250 GS', { slug: 'r-1250-gs', catalogType: TYPE.MOTORCYCLE, yearStart: 2018, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Buick', country: 'United States', models: [
    model('Regal', { yearStart: 1973, bodyType: 'Sedan' }),
    model('Century', { yearStart: 1973, yearEnd: 2005, bodyType: 'Sedan' }),
    model('LeSabre', { yearStart: 1959, yearEnd: 2005, bodyType: 'Sedan' }),
    model('Park Avenue', { yearStart: 1991, yearEnd: 2005, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'BYD', country: 'China', models: [
    model('Atto 3', { yearStart: 2022, bodyType: 'SUV' }),
    model('Dolphin', { yearStart: 2021, bodyType: 'Hatchback' }),
    model('Seal', { yearStart: 2022, bodyType: 'Sedan' }),
    model('Han', { yearStart: 2020, bodyType: 'Sedan' }),
    model('Tang', { yearStart: 2015, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Cadillac', country: 'United States', models: [
    model('ATS', { yearStart: 2012, yearEnd: 2019, bodyType: 'Sedan' }),
    model('CTS', { yearStart: 2002, yearEnd: 2019, bodyType: 'Sedan' }),
    model('Escalade', { yearStart: 1999, bodyType: 'SUV' }),
    model('XT5', { yearStart: 2016, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Chery', country: 'China', models: [
    model('Alia', { yearStart: 2006, yearEnd: 2012, bodyType: 'Sedan' }),
    model('Tiggo', { yearStart: 2005, bodyType: 'SUV' }),
    model('Tiggo 7 Pro', { yearStart: 2020, bodyType: 'SUV' }),
    model('Tiggo 8 Pro', { yearStart: 2020, bodyType: 'SUV' }),
    model('Arrizo 5', { yearStart: 2016, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Chevrolet', country: 'United States', models: [
    model('Spark', { yearStart: 1998, bodyType: 'Hatchback' }),
    model('Aveo', { yearStart: 2002, bodyType: 'Sedan' }),
    model('Cruze', { yearStart: 2008, bodyType: 'Sedan' }),
    model('Captiva', { yearStart: 2006, bodyType: 'SUV' }),
    model('Lacetti', { yearStart: 2002, bodyType: 'Hatchback' }),
    model('Camaro', { yearStart: 1966, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Chrysler', country: 'United States', models: [
    model('300C', { yearStart: 2004, bodyType: 'Sedan' }),
    model('PT Cruiser', { yearStart: 2000, yearEnd: 2010, bodyType: 'Hatchback' }),
    model('Sebring', { yearStart: 1995, yearEnd: 2010, bodyType: 'Sedan' }),
    model('Voyager', { yearStart: 1988, bodyType: 'Minivan' }),
  ]}),
  brand({ name: 'Citroen', country: 'France', models: [
    model('C3', { yearStart: 2002, bodyType: 'Hatchback' }),
    model('C4', { yearStart: 2004, bodyType: 'Hatchback' }),
    model('C-Elysee', { slug: 'c-elysee', yearStart: 2012, bodyType: 'Sedan' }),
    model('Berlingo', { yearStart: 1996, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('C5 Aircross', { slug: 'c5-aircross', yearStart: 2017, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Cupra', country: 'Spain', models: [
    model('Leon', { yearStart: 2018, bodyType: 'Hatchback' }),
    model('Formentor', { yearStart: 2020, bodyType: 'SUV' }),
    model('Born', { yearStart: 2021, bodyType: 'Hatchback' }),
    model('Ateca', { yearStart: 2018, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Dacia', country: 'Romania', models: [
    model('Sandero', { yearStart: 2007, bodyType: 'Hatchback' }),
    model('Duster', { yearStart: 2010, bodyType: 'SUV' }),
    model('Logan', { yearStart: 2004, bodyType: 'Sedan' }),
    model('Jogger', { yearStart: 2021, bodyType: 'Station Wagon' }),
  ]}),
  brand({ name: 'Daewoo', country: 'South Korea', models: [
    model('Espero', { yearStart: 1990, yearEnd: 1999, bodyType: 'Sedan' }),
    model('Lanos', { yearStart: 1997, yearEnd: 2002, bodyType: 'Sedan' }),
    model('Nubira', { yearStart: 1997, yearEnd: 2003, bodyType: 'Sedan' }),
    model('Matiz', { yearStart: 1998, yearEnd: 2015, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Daihatsu', country: 'Japan', models: [
    model('Charade', { yearStart: 1977, yearEnd: 2000, bodyType: 'Hatchback' }),
    model('Sirion', { yearStart: 1998, bodyType: 'Hatchback' }),
    model('Terios', { yearStart: 1997, bodyType: 'SUV' }),
    model('Copen', { yearStart: 2002, bodyType: 'Roadster' }),
  ]}),
  brand({ name: 'Dodge', country: 'United States', models: [
    model('Charger', { yearStart: 1966, bodyType: 'Sedan' }),
    model('Challenger', { yearStart: 1970, bodyType: 'Coupe' }),
    model('Durango', { yearStart: 1998, bodyType: 'SUV' }),
    model('Journey', { yearStart: 2008, yearEnd: 2020, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'DS Automobiles', slug: 'ds-automobiles', country: 'France', models: [
    model('DS 3', { slug: 'ds-3', yearStart: 2014, bodyType: 'Hatchback' }),
    model('DS 4', { slug: 'ds-4', yearStart: 2011, bodyType: 'Hatchback' }),
    model('DS 7', { slug: 'ds-7', yearStart: 2017, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Eagle', country: 'United States', models: [
    model('Talon', { yearStart: 1989, yearEnd: 1998, bodyType: 'Coupe' }),
    model('Vision', { yearStart: 1993, yearEnd: 1997, bodyType: 'Sedan' }),
    model('Summit', { yearStart: 1989, yearEnd: 1996, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Ferrari', country: 'Italy', models: [
    model('458 Italia', { slug: '458-italia', yearStart: 2009, yearEnd: 2015, bodyType: 'Coupe' }),
    model('488 GTB', { slug: '488-gtb', yearStart: 2015, yearEnd: 2019, bodyType: 'Coupe' }),
    model('F8 Tributo', { slug: 'f8-tributo', yearStart: 2019, bodyType: 'Coupe' }),
    model('Roma', { yearStart: 2020, bodyType: 'Coupe' }),
    model('Portofino', { yearStart: 2017, bodyType: 'Roadster' }),
  ]}),
  brand({ name: 'Fiat', country: 'Italy', models: [
    model('Egea', { yearStart: 2015, bodyType: 'Sedan' }),
    model('Linea', { yearStart: 2007, yearEnd: 2018, bodyType: 'Sedan' }),
    model('Fiorino', { yearStart: 2007, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Doblo', { yearStart: 2000, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Panda', { yearStart: 1980, bodyType: 'Hatchback' }),
    model('Punto', { yearStart: 1993, yearEnd: 2018, bodyType: 'Hatchback' }),
    model('Tipo', { yearStart: 1988, bodyType: 'Hatchback' }),
    model('500', { yearStart: 2007, bodyType: 'Hatchback' }),
    model('500L', { slug: '500l', yearStart: 2012, bodyType: 'MPV' }),
    model('500X', { slug: '500x', yearStart: 2014, bodyType: 'SUV' }),
    model('Bravo', { yearStart: 1995, yearEnd: 2014, bodyType: 'Hatchback' }),
    model('Albea', { yearStart: 2002, yearEnd: 2012, bodyType: 'Sedan' }),
    model('Palio', { yearStart: 1996, yearEnd: 2017, bodyType: 'Hatchback' }),
    model('Siena', { yearStart: 1996, yearEnd: 2012, bodyType: 'Sedan' }),
    model('Marea', { yearStart: 1996, yearEnd: 2007, bodyType: 'Sedan' }),
    model('Uno', { yearStart: 1983, yearEnd: 2013, bodyType: 'Hatchback' }),
    model('Tempra', { yearStart: 1990, yearEnd: 1999, bodyType: 'Sedan' }),
    model('Ducato', { yearStart: 1981, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
  ]}),
  brand({ name: 'Ford', country: 'United States', models: [
    model('Focus', { yearStart: 1998, bodyType: 'Hatchback' }),
    model('Fiesta', { yearStart: 1976, bodyType: 'Hatchback' }),
    model('Courier', { yearStart: 1991, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Puma', { yearStart: 2019, bodyType: 'SUV' }),
    model('Kuga', { yearStart: 2008, bodyType: 'SUV' }),
    model('EcoSport', { slug: 'ecosport', yearStart: 2003, bodyType: 'SUV' }),
    model('Mondeo', { yearStart: 1993, yearEnd: 2022, bodyType: 'Sedan' }),
    model('Transit Courier', { slug: 'transit-courier', yearStart: 2014, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Tourneo Courier', { slug: 'tourneo-courier', yearStart: 2014, catalogType: TYPE.COMMERCIAL, bodyType: 'Van' }),
    model('Mustang', { yearStart: 1964, bodyType: 'Coupe' }),
    model('Ranger', { yearStart: 1982, catalogType: TYPE.COMMERCIAL, bodyType: 'Pickup' }),
  ]}),
  brand({ name: 'Geely', country: 'China', models: [
    model('Emgrand', { yearStart: 2009, bodyType: 'Sedan' }),
    model('Coolray', { yearStart: 2018, bodyType: 'SUV' }),
    model('Geometry C', { slug: 'geometry-c', yearStart: 2020, bodyType: 'SUV' }),
    model('Monjaro', { yearStart: 2021, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Honda', country: 'Japan', models: [
    model('Civic', { yearStart: 1972, bodyType: 'Sedan' }),
    model('City', { yearStart: 1981, bodyType: 'Sedan' }),
    model('CR-V', { slug: 'cr-v', yearStart: 1995, bodyType: 'SUV' }),
    model('Jazz', { yearStart: 2001, bodyType: 'Hatchback' }),
    model('HR-V', { slug: 'hr-v', yearStart: 1998, bodyType: 'SUV' }),
    model('Accord', { yearStart: 1976, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Hyundai', country: 'South Korea', models: [
    model('i20', { yearStart: 2008, bodyType: 'Hatchback' }),
    model('i30', { yearStart: 2007, bodyType: 'Hatchback' }),
    model('Tucson', { yearStart: 2004, bodyType: 'SUV' }),
    model('Elantra', { yearStart: 1990, bodyType: 'Sedan' }),
    model('Accent Blue', { slug: 'accent-blue', yearStart: 2011, bodyType: 'Sedan' }),
    model('Bayon', { yearStart: 2021, bodyType: 'SUV' }),
    model('Kona', { yearStart: 2017, bodyType: 'SUV' }),
    model('Santa Fe', { slug: 'santa-fe', yearStart: 2000, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'I-GO', slug: 'i-go', country: 'China', models: [
    reviewModel('I-Go EV', { yearStart: 2020, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Ikco', country: 'Iran', models: [
    model('Samand', { yearStart: 2001, bodyType: 'Sedan' }),
    model('Dena', { yearStart: 2014, bodyType: 'Sedan' }),
    model('Runna', { yearStart: 2012, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Infiniti', country: 'Japan', models: [
    model('Q30', { yearStart: 2015, yearEnd: 2019, bodyType: 'Hatchback' }),
    model('Q50', { yearStart: 2013, bodyType: 'Sedan' }),
    model('QX30', { slug: 'qx30', yearStart: 2016, yearEnd: 2020, bodyType: 'SUV' }),
    model('QX60', { slug: 'qx60', yearStart: 2012, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Jaguar', country: 'United Kingdom', models: [
    model('XE', { yearStart: 2015, bodyType: 'Sedan' }),
    model('XF', { yearStart: 2007, bodyType: 'Sedan' }),
    model('XJ', { yearStart: 1968, yearEnd: 2019, bodyType: 'Sedan' }),
    model('F-Pace', { slug: 'f-pace', yearStart: 2016, bodyType: 'SUV' }),
    model('E-Pace', { slug: 'e-pace', yearStart: 2017, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Jiayuan', country: 'China', models: [
    model('Komi', { yearStart: 2019, bodyType: 'Microcar' }),
    reviewModel('City Fun', { yearStart: 2021, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Kia', country: 'South Korea', models: [
    model('Rio', { yearStart: 1999, bodyType: 'Hatchback' }),
    model('Ceed', { yearStart: 2006, bodyType: 'Hatchback' }),
    model('Sportage', { yearStart: 1993, bodyType: 'SUV' }),
    model('Picanto', { yearStart: 2004, bodyType: 'Hatchback' }),
    model('Cerato', { yearStart: 2003, bodyType: 'Sedan' }),
    model('Stonic', { yearStart: 2017, bodyType: 'SUV' }),
    model('Sorento', { yearStart: 2002, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Kuba', country: 'Turkey', type: TYPE.MOTORCYCLE, models: [
    model('Blueberry', { catalogType: TYPE.MOTORCYCLE, yearStart: 2018, bodyType: 'Motosiklet' }),
    model('Superlight 200', { slug: 'superlight-200', catalogType: TYPE.MOTORCYCLE, yearStart: 2012, bodyType: 'Motosiklet' }),
    model('Trendy 50', { slug: 'trendy-50', catalogType: TYPE.MOTORCYCLE, yearStart: 2016, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Lada', country: 'Russia', models: [
    model('Niva', { yearStart: 1977, bodyType: 'SUV' }),
    model('Samara', { yearStart: 1984, yearEnd: 2013, bodyType: 'Hatchback' }),
    model('Granta', { yearStart: 2011, bodyType: 'Sedan' }),
    model('Vesta', { yearStart: 2015, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Lamborghini', country: 'Italy', models: [
    model('Gallardo', { yearStart: 2003, yearEnd: 2013, bodyType: 'Coupe' }),
    model('Huracan', { yearStart: 2014, bodyType: 'Coupe' }),
    model('Aventador', { yearStart: 2011, yearEnd: 2022, bodyType: 'Coupe' }),
    model('Urus', { yearStart: 2018, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Lancia', country: 'Italy', models: [
    model('Ypsilon', { yearStart: 1995, bodyType: 'Hatchback' }),
    model('Delta', { yearStart: 1979, bodyType: 'Hatchback' }),
    model('Lybra', { yearStart: 1998, yearEnd: 2005, bodyType: 'Sedan' }),
    model('Thema', { yearStart: 1984, yearEnd: 2014, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Leapmotor', country: 'China', models: [
    model('T03', { yearStart: 2020, bodyType: 'Hatchback' }),
    model('C10', { yearStart: 2024, bodyType: 'SUV' }),
    model('C11', { yearStart: 2021, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Lexus', country: 'Japan', models: [
    model('IS', { yearStart: 1999, bodyType: 'Sedan' }),
    model('ES', { yearStart: 1989, bodyType: 'Sedan' }),
    model('NX', { yearStart: 2014, bodyType: 'SUV' }),
    model('RX', { yearStart: 1998, bodyType: 'SUV' }),
    model('UX', { yearStart: 2018, bodyType: 'SUV' }),
    model('LS', { yearStart: 1989, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Lincoln', country: 'United States', models: [
    model('Town Car', { slug: 'town-car', yearStart: 1981, yearEnd: 2011, bodyType: 'Sedan' }),
    model('MKZ', { yearStart: 2006, yearEnd: 2020, bodyType: 'Sedan' }),
    model('Navigator', { yearStart: 1997, bodyType: 'SUV' }),
    model('Corsair', { yearStart: 2019, bodyType: 'SUV' }),
    model('Aviator', { yearStart: 2002, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Lotus', country: 'United Kingdom', models: [
    model('Elise', { yearStart: 1996, yearEnd: 2021, bodyType: 'Roadster' }),
    model('Evora', { yearStart: 2008, yearEnd: 2021, bodyType: 'Coupe' }),
    model('Emira', { yearStart: 2021, bodyType: 'Coupe' }),
    model('Eletre', { yearStart: 2022, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Luqi', country: 'China', type: TYPE.MOTORCYCLE, models: [
    reviewModel('HL 3.0', { catalogType: TYPE.MOTORCYCLE, yearStart: 2020, bodyType: 'Motosiklet' }),
    reviewModel('EV600', { catalogType: TYPE.MOTORCYCLE, yearStart: 2021, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Marcos', country: 'United Kingdom', models: [
    model('Mantis', { yearStart: 1970, yearEnd: 1972, bodyType: 'Coupe' }),
    model('Mantula', { yearStart: 1983, yearEnd: 2000, bodyType: 'Coupe' }),
    model('Mini Marcos', { slug: 'mini-marcos', yearStart: 1965, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Maserati', country: 'Italy', models: [
    model('Ghibli', { yearStart: 2013, bodyType: 'Sedan' }),
    model('Levante', { yearStart: 2016, bodyType: 'SUV' }),
    model('Quattroporte', { yearStart: 1963, bodyType: 'Sedan' }),
    model('Grecale', { yearStart: 2022, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Mazda', country: 'Japan', models: [
    model('2', { yearStart: 2002, bodyType: 'Hatchback' }),
    model('3', { yearStart: 2003, bodyType: 'Sedan' }),
    model('6', { yearStart: 2002, bodyType: 'Sedan' }),
    model('CX-3', { slug: 'cx-3', yearStart: 2015, bodyType: 'SUV' }),
    model('CX-5', { slug: 'cx-5', yearStart: 2012, bodyType: 'SUV' }),
    model('CX-30', { slug: 'cx-30', yearStart: 2019, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'McLaren', country: 'United Kingdom', models: [
    model('570S', { yearStart: 2015, yearEnd: 2021, bodyType: 'Coupe' }),
    model('720S', { yearStart: 2017, bodyType: 'Coupe' }),
    model('GT', { yearStart: 2019, bodyType: 'Coupe' }),
    model('Artura', { yearStart: 2021, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Mercedes-Benz', slug: 'mercedes-benz', country: 'Germany', models: [
    model('A Serisi', { slug: 'a-serisi', yearStart: 1997, bodyType: 'Hatchback' }),
    model('C Serisi', { slug: 'c-serisi', yearStart: 1993, bodyType: 'Sedan' }),
    model('E Serisi', { slug: 'e-serisi', yearStart: 1993, bodyType: 'Sedan' }),
    model('CLA', { yearStart: 2013, bodyType: 'Sedan' }),
    model('GLA', { yearStart: 2013, bodyType: 'SUV' }),
    model('GLC', { yearStart: 2015, bodyType: 'SUV' }),
    model('Vito', { yearStart: 1996, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Sprinter', { yearStart: 1995, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Citan', { yearStart: 2012, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
  ]}),
  brand({ name: 'MG', country: 'United Kingdom', models: [
    model('ZS', { yearStart: 2017, bodyType: 'SUV' }),
    model('HS', { yearStart: 2018, bodyType: 'SUV' }),
    model('MG4', { slug: 'mg4', yearStart: 2022, bodyType: 'Hatchback' }),
    model('MG5', { slug: 'mg5', yearStart: 2020, bodyType: 'Station Wagon' }),
    model('Marvel R', { slug: 'marvel-r', yearStart: 2021, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Micro', country: 'Switzerland', models: [
    model('Microlino', { yearStart: 2022, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Mini', country: 'United Kingdom', models: [
    model('Cooper', { yearStart: 2001, bodyType: 'Hatchback' }),
    model('Countryman', { yearStart: 2010, bodyType: 'SUV' }),
    model('Clubman', { yearStart: 2007, bodyType: 'Station Wagon' }),
    model('Cabrio', { yearStart: 2004, bodyType: 'Roadster' }),
  ]}),
  brand({ name: 'Mitsubishi', country: 'Japan', models: [
    model('Lancer', { yearStart: 1973, bodyType: 'Sedan' }),
    model('Colt', { yearStart: 1962, bodyType: 'Hatchback' }),
    model('ASX', { yearStart: 2010, bodyType: 'SUV' }),
    model('Outlander', { yearStart: 2001, bodyType: 'SUV' }),
    model('Pajero', { yearStart: 1982, bodyType: 'SUV' }),
    model('Eclipse Cross', { slug: 'eclipse-cross', yearStart: 2017, bodyType: 'SUV' }),
    model('L200', { slug: 'l200', catalogType: TYPE.COMMERCIAL, yearStart: 1978, bodyType: 'Pickup' }),
  ]}),
  brand({ name: 'Morgan', country: 'United Kingdom', models: [
    model('Plus Four', { slug: 'plus-four', yearStart: 1950, bodyType: 'Roadster' }),
    model('Plus Six', { slug: 'plus-six', yearStart: 2019, bodyType: 'Roadster' }),
    model('3 Wheeler', { slug: '3-wheeler', yearStart: 2011, bodyType: 'Roadster' }),
  ]}),
  brand({ name: 'Nieve', country: 'China', models: [
    reviewModel('EV Mini', { yearStart: 2022, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Nissan', country: 'Japan', models: [
    model('Micra', { yearStart: 1982, bodyType: 'Hatchback' }),
    model('Almera', { yearStart: 1995, bodyType: 'Sedan' }),
    model('Note', { yearStart: 2004, bodyType: 'Hatchback' }),
    model('Juke', { yearStart: 2010, bodyType: 'SUV' }),
    model('Qashqai', { yearStart: 2006, bodyType: 'SUV' }),
    model('X-Trail', { slug: 'x-trail', yearStart: 2000, bodyType: 'SUV' }),
    model('Navara', { yearStart: 1985, catalogType: TYPE.COMMERCIAL, bodyType: 'Pickup' }),
    model('Pulsar', { yearStart: 1978, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Opel', country: 'Germany', models: [
    model('Corsa', { yearStart: 1982, bodyType: 'Hatchback' }),
    model('Astra', { yearStart: 1991, bodyType: 'Hatchback' }),
    model('Insignia', { yearStart: 2008, bodyType: 'Sedan' }),
    model('Mokka', { yearStart: 2012, bodyType: 'SUV' }),
    model('Crossland', { yearStart: 2017, bodyType: 'SUV' }),
    model('Combo', { yearStart: 1986, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
  ]}),
  brand({ name: 'Ortimobil', country: 'Turkey', models: [
    reviewModel('E-City', { yearStart: 2023, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Peugeot', country: 'France', models: [
    model('208', { yearStart: 2012, bodyType: 'Hatchback' }),
    model('308', { yearStart: 2007, bodyType: 'Hatchback' }),
    model('508', { yearStart: 2010, bodyType: 'Sedan' }),
    model('2008', { yearStart: 2013, bodyType: 'SUV' }),
    model('3008', { yearStart: 2008, bodyType: 'SUV' }),
    model('Partner', { yearStart: 1996, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Rifter', { yearStart: 2018, bodyType: 'Van' }),
    model('Boxer', { yearStart: 1994, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
  ]}),
  brand({ name: 'Plymouth', country: 'United States', models: [
    model('Neon', { yearStart: 1994, yearEnd: 2001, bodyType: 'Sedan' }),
    model('Voyager', { yearStart: 1988, yearEnd: 2000, bodyType: 'Minivan' }),
    model('Prowler', { yearStart: 1997, yearEnd: 2002, bodyType: 'Roadster' }),
    model('Sundance', { yearStart: 1987, yearEnd: 1994, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Polestar', country: 'Sweden', models: [
    model('2', { yearStart: 2020, bodyType: 'Liftback' }),
    model('3', { yearStart: 2022, bodyType: 'SUV' }),
    model('4', { yearStart: 2023, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Pontiac', country: 'United States', models: [
    model('Firebird', { yearStart: 1967, yearEnd: 2002, bodyType: 'Coupe' }),
    model('Grand Prix', { slug: 'grand-prix', yearStart: 1962, yearEnd: 2008, bodyType: 'Sedan' }),
    model('Bonneville', { yearStart: 1957, yearEnd: 2005, bodyType: 'Sedan' }),
    model('Trans Am', { slug: 'trans-am', yearStart: 1969, yearEnd: 2002, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Porsche', country: 'Germany', models: [
    model('911', { yearStart: 1964, bodyType: 'Coupe' }),
    model('Boxster', { yearStart: 1996, bodyType: 'Roadster' }),
    model('Cayenne', { yearStart: 2002, bodyType: 'SUV' }),
    model('Macan', { yearStart: 2014, bodyType: 'SUV' }),
    model('Panamera', { yearStart: 2009, bodyType: 'Sedan' }),
    model('Taycan', { yearStart: 2019, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Proton', country: 'Malaysia', models: [
    model('Saga', { yearStart: 1985, bodyType: 'Sedan' }),
    model('Wira', { yearStart: 1993, yearEnd: 2009, bodyType: 'Sedan' }),
    model('Gen-2', { slug: 'gen-2', yearStart: 2004, yearEnd: 2012, bodyType: 'Hatchback' }),
    model('Persona', { yearStart: 2007, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Rainwoll', country: 'China', models: [
    reviewModel('Mini EV', { yearStart: 2022, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Reeder', country: 'Turkey', models: [
    reviewModel('ReeV Fancy', { yearStart: 2024, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Regal Raptor', slug: 'regal-raptor', country: 'China', type: TYPE.MOTORCYCLE, models: [
    model('Daytona 250', { slug: 'daytona-250', catalogType: TYPE.MOTORCYCLE, yearStart: 2014, bodyType: 'Motosiklet' }),
    model('Pilder 125', { slug: 'pilder-125', catalogType: TYPE.MOTORCYCLE, yearStart: 2016, bodyType: 'Motosiklet' }),
    model('Spyder', { catalogType: TYPE.MOTORCYCLE, yearStart: 2018, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Relive', country: 'China', models: [
    reviewModel('Urban EV', { yearStart: 2023, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Renault', country: 'France', models: [
    model('Clio', { yearStart: 1990, bodyType: 'Hatchback' }),
    model('Megane', { yearStart: 1995, bodyType: 'Sedan' }),
    model('Symbol', { yearStart: 1999, bodyType: 'Sedan' }),
    model('Fluence', { yearStart: 2009, yearEnd: 2016, bodyType: 'Sedan' }),
    model('Taliant', { yearStart: 2021, bodyType: 'Sedan' }),
    model('Captur', { yearStart: 2013, bodyType: 'SUV' }),
    model('Kadjar', { yearStart: 2015, yearEnd: 2022, bodyType: 'SUV' }),
    model('Koleos', { yearStart: 2007, bodyType: 'SUV' }),
    model('Austral', { yearStart: 2022, bodyType: 'SUV' }),
    model('Scenic', { yearStart: 1996, bodyType: 'MPV' }),
    model('Kangoo', { yearStart: 1997, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Trafic', { yearStart: 1980, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Master', { yearStart: 1980, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Laguna', { yearStart: 1993, yearEnd: 2015, bodyType: 'Sedan' }),
    model('Latitude', { yearStart: 2010, yearEnd: 2015, bodyType: 'Sedan' }),
    model('Twingo', { yearStart: 1992, bodyType: 'Hatchback' }),
    model('Zoe', { yearStart: 2012, yearEnd: 2024, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'RKS', country: 'Turkey', type: TYPE.MOTORCYCLE, models: [
    model('Newlight', { catalogType: TYPE.MOTORCYCLE, yearStart: 2020, bodyType: 'Motosiklet' }),
    model('Freccia 150', { slug: 'freccia-150', catalogType: TYPE.MOTORCYCLE, yearStart: 2019, bodyType: 'Motosiklet' }),
    model('M5', { catalogType: TYPE.MOTORCYCLE, yearStart: 2021, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Rolls-Royce', slug: 'rolls-royce', country: 'United Kingdom', models: [
    model('Ghost', { yearStart: 2009, bodyType: 'Sedan' }),
    model('Phantom', { yearStart: 1925, bodyType: 'Sedan' }),
    model('Cullinan', { yearStart: 2018, bodyType: 'SUV' }),
    model('Wraith', { yearStart: 2013, yearEnd: 2023, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Rover', country: 'United Kingdom', models: [
    model('25', { yearStart: 1999, yearEnd: 2005, bodyType: 'Hatchback' }),
    model('45', { yearStart: 1999, yearEnd: 2005, bodyType: 'Sedan' }),
    model('75', { yearStart: 1998, yearEnd: 2005, bodyType: 'Sedan' }),
    model('200', { yearStart: 1984, yearEnd: 1999, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Saab', country: 'Sweden', models: [
    model('900', { yearStart: 1978, yearEnd: 1998, bodyType: 'Hatchback' }),
    model('9-3', { slug: '9-3', yearStart: 1998, yearEnd: 2014, bodyType: 'Sedan' }),
    model('9-5', { slug: '9-5', yearStart: 1997, yearEnd: 2012, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Saipa', country: 'Iran', models: [
    model('Tiba', { yearStart: 2008, bodyType: 'Sedan' }),
    model('Saina', { yearStart: 2016, bodyType: 'Sedan' }),
    model('Shahin', { yearStart: 2020, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Seat', country: 'Spain', models: [
    model('Ibiza', { yearStart: 1984, bodyType: 'Hatchback' }),
    model('Leon', { yearStart: 1999, bodyType: 'Hatchback' }),
    model('Ateca', { yearStart: 2016, bodyType: 'SUV' }),
    model('Arona', { yearStart: 2017, bodyType: 'SUV' }),
    model('Toledo', { yearStart: 1991, yearEnd: 2019, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Skoda', country: 'Czech Republic', models: [
    model('Fabia', { yearStart: 1999, bodyType: 'Hatchback' }),
    model('Octavia', { yearStart: 1996, bodyType: 'Sedan' }),
    model('Superb', { yearStart: 2001, bodyType: 'Sedan' }),
    model('Scala', { yearStart: 2019, bodyType: 'Hatchback' }),
    model('Karoq', { yearStart: 2017, bodyType: 'SUV' }),
    model('Kamiq', { yearStart: 2019, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Smart', country: 'Germany', models: [
    model('Fortwo', { yearStart: 1998, bodyType: 'Hatchback' }),
    model('Forfour', { yearStart: 2004, bodyType: 'Hatchback' }),
    model('#1', { slug: '1', yearStart: 2022, bodyType: 'SUV' }),
    model('#3', { slug: '3', yearStart: 2023, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Subaru', country: 'Japan', models: [
    model('Impreza', { yearStart: 1992, bodyType: 'Sedan' }),
    model('Forester', { yearStart: 1997, bodyType: 'SUV' }),
    model('XV', { yearStart: 2011, bodyType: 'SUV' }),
    model('Legacy', { yearStart: 1989, bodyType: 'Sedan' }),
    model('Outback', { yearStart: 1994, bodyType: 'Station Wagon' }),
    model('BRZ', { yearStart: 2012, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Suzuki', country: 'Japan', models: [
    model('Swift', { yearStart: 1983, bodyType: 'Hatchback' }),
    model('Vitara', { yearStart: 1988, bodyType: 'SUV' }),
    model('SX4', { slug: 'sx4', yearStart: 2006, bodyType: 'Hatchback' }),
    model('Jimny', { yearStart: 1970, bodyType: 'SUV' }),
    model('Baleno', { yearStart: 1995, bodyType: 'Hatchback' }),
    model('S-Cross', { slug: 's-cross', yearStart: 2013, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'Tata', country: 'India', models: [
    model('Indica', { yearStart: 1998, yearEnd: 2018, bodyType: 'Hatchback' }),
    model('Indigo', { yearStart: 2002, yearEnd: 2016, bodyType: 'Sedan' }),
    model('Nano', { yearStart: 2008, yearEnd: 2018, bodyType: 'Hatchback' }),
    model('Safari', { yearStart: 1998, bodyType: 'SUV' }),
    model('Tiago', { yearStart: 2016, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Tesla', country: 'United States', models: [
    model('Model S', { slug: 'model-s', yearStart: 2012, bodyType: 'Sedan' }),
    model('Model 3', { slug: 'model-3', yearStart: 2017, bodyType: 'Sedan' }),
    model('Model X', { slug: 'model-x', yearStart: 2015, bodyType: 'SUV' }),
    model('Model Y', { slug: 'model-y', yearStart: 2020, bodyType: 'SUV' }),
    model('Cybertruck', { yearStart: 2023, bodyType: 'Pickup' }),
  ]}),
  brand({ name: 'The London Taxi', slug: 'the-london-taxi', country: 'United Kingdom', type: TYPE.COMMERCIAL, models: [
    model('TX1', { catalogType: TYPE.COMMERCIAL, yearStart: 1997, bodyType: 'Taxi' }),
    model('TX4', { catalogType: TYPE.COMMERCIAL, yearStart: 2006, bodyType: 'Taxi' }),
    model('TX5', { catalogType: TYPE.COMMERCIAL, yearStart: 2017, bodyType: 'Taxi' }),
  ]}),
  brand({ name: 'Tofas', country: 'Turkey', models: [
    model('Sahin', { yearStart: 1981, yearEnd: 2002, bodyType: 'Sedan' }),
    model('Dogan', { yearStart: 1988, yearEnd: 2002, bodyType: 'Sedan' }),
    model('Kartal', { yearStart: 1985, yearEnd: 2002, bodyType: 'Station Wagon' }),
    model('Serce', { yearStart: 1983, yearEnd: 1995, bodyType: 'Sedan' }),
    model('Murat 131', { slug: 'murat-131', yearStart: 1977, yearEnd: 1988, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'TOGG', country: 'Turkey', models: [
    model('T10X', { yearStart: 2023, bodyType: 'SUV' }),
    model('T10F', { yearStart: 2025, bodyType: 'Sedan' }),
  ]}),
  brand({ name: 'Toyota', country: 'Japan', models: [
    model('Corolla', { yearStart: 1966, bodyType: 'Sedan' }),
    model('Yaris', { yearStart: 1999, bodyType: 'Hatchback' }),
    model('C-HR', { slug: 'c-hr', yearStart: 2016, bodyType: 'SUV' }),
    model('Auris', { yearStart: 2006, yearEnd: 2018, bodyType: 'Hatchback' }),
    model('Camry', { yearStart: 1982, bodyType: 'Sedan' }),
    model('Hilux', { yearStart: 1968, catalogType: TYPE.COMMERCIAL, bodyType: 'Pickup' }),
    model('RAV4', { slug: 'rav4', yearStart: 1994, bodyType: 'SUV' }),
    model('Prius', { yearStart: 1997, bodyType: 'Hatchback' }),
  ]}),
  brand({ name: 'Vanderhall', country: 'United States', type: TYPE.MOTORCYCLE, models: [
    model('Venice', { catalogType: TYPE.MOTORCYCLE, yearStart: 2017, bodyType: 'Roadster' }),
    model('Carmel', { catalogType: TYPE.MOTORCYCLE, yearStart: 2019, bodyType: 'Roadster' }),
    model('Navarro', { catalogType: TYPE.MOTORCYCLE, yearStart: 2021, bodyType: 'Roadster' }),
  ]}),
  brand({ name: 'Volkswagen', country: 'Germany', models: [
    model('Polo', { yearStart: 1975, bodyType: 'Hatchback' }),
    model('Golf', { yearStart: 1974, bodyType: 'Hatchback' }),
    model('Passat', { yearStart: 1973, bodyType: 'Sedan' }),
    model('Jetta', { yearStart: 1979, bodyType: 'Sedan' }),
    model('Bora', { yearStart: 1998, yearEnd: 2005, bodyType: 'Sedan' }),
    model('Arteon', { yearStart: 2017, bodyType: 'Liftback' }),
    model('Tiguan', { yearStart: 2007, bodyType: 'SUV' }),
    model('Touareg', { yearStart: 2002, bodyType: 'SUV' }),
    model('T-Roc', { slug: 't-roc', yearStart: 2017, bodyType: 'SUV' }),
    model('T-Cross', { slug: 't-cross', yearStart: 2018, bodyType: 'SUV' }),
    model('Taigo', { yearStart: 2021, bodyType: 'SUV' }),
    model('Caddy', { yearStart: 1980, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Transporter', { yearStart: 1950, catalogType: TYPE.COMMERCIAL, bodyType: 'Panelvan' }),
    model('Caravelle', { yearStart: 1979, catalogType: TYPE.COMMERCIAL, bodyType: 'Van' }),
    model('Amarok', { yearStart: 2010, catalogType: TYPE.COMMERCIAL, bodyType: 'Pickup' }),
    model('Touran', { yearStart: 2003, bodyType: 'MPV' }),
    model('Sharan', { yearStart: 1995, yearEnd: 2022, bodyType: 'MPV' }),
    model('Beetle', { yearStart: 1938, yearEnd: 2019, bodyType: 'Coupe' }),
    model('Scirocco', { yearStart: 1974, yearEnd: 2017, bodyType: 'Coupe' }),
  ]}),
  brand({ name: 'Volta', country: 'Turkey', type: TYPE.MOTORCYCLE, models: [
    reviewModel('VS1', { catalogType: TYPE.MOTORCYCLE, yearStart: 2021, bodyType: 'Motosiklet' }),
    reviewModel('VB1', { catalogType: TYPE.MOTORCYCLE, yearStart: 2021, bodyType: 'Motosiklet' }),
    reviewModel('VM4', { catalogType: TYPE.MOTORCYCLE, yearStart: 2022, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'Volvo', country: 'Sweden', models: [
    model('S60', { yearStart: 2000, bodyType: 'Sedan' }),
    model('S90', { yearStart: 1996, bodyType: 'Sedan' }),
    model('V40', { yearStart: 1995, bodyType: 'Hatchback' }),
    model('V60', { yearStart: 2010, bodyType: 'Station Wagon' }),
    model('XC40', { yearStart: 2017, bodyType: 'SUV' }),
    model('XC60', { yearStart: 2008, bodyType: 'SUV' }),
    model('XC90', { yearStart: 2002, bodyType: 'SUV' }),
  ]}),
  brand({ name: 'XEV', country: 'Italy', models: [
    model('Yoyo', { yearStart: 2021, bodyType: 'Microcar' }),
  ]}),
  brand({ name: 'Yuki', country: 'Turkey', type: TYPE.MOTORCYCLE, models: [
    model('Legend 50', { slug: 'legend-50', catalogType: TYPE.MOTORCYCLE, yearStart: 2018, bodyType: 'Motosiklet' }),
    model('Casper', { catalogType: TYPE.MOTORCYCLE, yearStart: 2019, bodyType: 'Motosiklet' }),
    model('Storm', { catalogType: TYPE.MOTORCYCLE, yearStart: 2020, bodyType: 'Motosiklet' }),
  ]}),
  brand({ name: 'ZAZ', country: 'Ukraine', models: [
    model('Tavria', { yearStart: 1987, yearEnd: 2011, bodyType: 'Hatchback' }),
    model('Slavuta', { yearStart: 1999, yearEnd: 2011, bodyType: 'Liftback' }),
    model('Forza', { yearStart: 2011, yearEnd: 2014, bodyType: 'Sedan' }),
  ]}),
];

module.exports = {
  PHASE1_VEHICLE_MODEL_BRANDS,
  VEHICLE_CATALOG_PHASE1_TYPE: TYPE,
  VEHICLE_CATALOG_PHASE1_SOURCE: SOURCE,
};
